[nox]
addr = ":5432"
root = "./web/"
# api = "./abi/libapi.so"
api = "../../nox-go-test/libapi2.so"

[nox.tls]
enabled = false
cert_file = "./cert.pem"
key_file = "./key.pem"
# protocols = ["tlsv1.2", "tlsv1.3"] do i want this?
ciphers = "n/a"

# [build]
# this will one day include information on how nox can build APIs

[nox.dependencies]
"postgres" = "https://noxrepository.com/creator/posgres"
